version: "3"
services:
  mysql: 
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: astri
  mongo:
    image: mongo
    deploy: 
      placement: 
        constraints:
          - node.role == manager
          - node.id == j8rlwbtdksxzjzbx03fmmjeb6
